name: AtomPub API
id: AtomPub
author_name: Endevver
description: Provides enhanced support for the AtomPub blog publishing API.
version: 1.0

applications:
    atom:
        handler: AtomPub::AtomServer
config_settings:
    AtomApp:
        type: HASH
        default:
            1.0: AtomPub::AtomServer::Weblog
